[package]
name = "libforestdb-sys"
version = "0.1.0"
authors = ["Valerii Hiora <valerii.hiora@gmail.com>"]
links = "forestdb"
license = "MIT"
description = "ForestDB native lib"
repository = "https://github.com/vhbit/sherwood"
build = "src/build.rs"

[dependencies]
regex = "= 0.1.10"
